from dataclasses import dataclass


class DataIngestionAtrifact:
    feature_store_file_path : str
    train_file_path: str
    test_file_path : str
    
class DataValidationArtifact:...
class DataTransformationAtrifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...
